/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package componente;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * Mayra Huamani Huaman
 */
public class Login extends javax.swing.JFrame {

    private UserDatabase userDatabase; // Base de datos de usuarios
    private int intentos = 0; // Contador de intentos de inicio de sesión
    private static final int MAX_INTENTOS = 3; // Número máximo de intentos de inicio de sesión permitidos

    public Login(UserDatabase userDatabase) {
        this.userDatabase = new UserDatabase(); // Inicializa la base de datos de usuarios
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labelPasswordUser = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        showPassword = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("INICIAR SESION");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre de usuario");

        labelUserName.setBackground(new java.awt.Color(255, 255, 255));
        labelUserName.setForeground(new java.awt.Color(204, 204, 204));
        labelUserName.setText("Ingresa tu nombre de usuario");
        labelUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        labelUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelUserNameMousePressed(evt);
            }
        });
        labelUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelUserNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");

        labelPasswordUser.setBackground(new java.awt.Color(255, 255, 255));
        labelPasswordUser.setText("*************");
        labelPasswordUser.setToolTipText("");
        labelPasswordUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        labelPasswordUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelPasswordUserMousePressed(evt);
            }
        });
        labelPasswordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelPasswordUserActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(51, 153, 255));
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("INICIAR SESION");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("¿No tienes cuenta? Crearla ahora");

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(51, 153, 255));
        btnRegister.setText("REGISTRARSE");
        btnRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        showPassword.setBackground(new java.awt.Color(255, 255, 255));
        showPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        showPassword.setForeground(new java.awt.Color(0, 0, 0));
        showPassword.setText("Mostrar contraseña");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUserName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPasswordUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(47, 47, 47)
                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPassword)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgdoctor.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 350, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String userName = labelUserName.getText(); // Obtiene el nombre de usuario del campo de texto
        String passwordUser = new String(labelPasswordUser.getText()); // Obtiene la contraseña del campo de texto
        boolean loginExitoso = false; // Indicar si el inicio de sesión fue exitoso o fallido

        if (userName.isEmpty() || passwordUser.isEmpty() || userName.equals("Ingresa tu nombre de usuario") || passwordUser.equals("*************")) {
            JOptionPane.showMessageDialog(null, "No puede haber un campo vacío."); // Muestra un mensaje si algún campo está vacío o tiene valores predeterminados
            return;
        }

        for (int i = 0; i < userDatabase.usercount; i++) {
            if (userDatabase.usernames.get(i).equals(userName) && userDatabase.passwords.get(i).equals(passwordUser)) {
                loginExitoso = true; // Indica que el inicio de sesión fue exitoso si se encuentra una coincidencia de nombre de usuario y contraseña en la base de datos
                break; // Sale del bucle una vez encontrada la coincidencia
            }
        }

        if (loginExitoso) {
            JOptionPane.showMessageDialog(null, String.format("Login exitoso, bienvenido %s", userName)); // Muestra un mensaje de bienvenida
            intentos = 0; // Reinicia el contador de intentos fallidos

            MenuPrincipal menuPrincipal = new MenuPrincipal(); // Crea e inicializa la ventana del menú principal
            menuPrincipal.setVisible(true); // Hace visible el menú principal
            menuPrincipal.setLocationRelativeTo(null); // Centra el menú principal en la pantalla
            this.dispose(); // Cierra la ventana de inicio de sesión
        } else {
            intentos++; // Incrementa el contador de intentos fallidos
            if (intentos >= MAX_INTENTOS) {
                JOptionPane.showMessageDialog(null, "Ha alcanzado el límite máximo de intentos. Vuelva más tarde.");
                btnLogin.setEnabled(false); // Deshabilita el botón de inicio de sesión
            } else {
                JOptionPane.showMessageDialog(null, String.format("Usuario y/o contraseña incorrecta. Intento fallido %d de %d", intentos, MAX_INTENTOS)); // Muestra un mensaje indicando el intento fallido
                labelPasswordUser.setText("*************"); // Restablece el campo de contraseña
                labelPasswordUser.setForeground(Color.gray); // Cambia el color del texto de la contraseña a gris
                labelUserName.setText("Ingresa tu nombre de usuario"); // Restablece el campo de nombre de usuario
                labelUserName.setForeground(Color.gray); // Cambia el color del texto del nombre de usuario a gris
            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        Register registerMenu = new Register(this.userDatabase); // Crea una nueva instancia de la ventana de registro con la base de datos de usuarios
        registerMenu.setVisible(true); // Hace visible la ventana de registro
        registerMenu.setLocationRelativeTo(null); // Centra la ventana de registro en la pantalla
        this.dispose(); // Cierra la ventana actual de inicio de sesión
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void labelUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelUserNameActionPerformed

    }//GEN-LAST:event_labelUserNameActionPerformed

    private void labelUserNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserNameMousePressed
        if (labelUserName.getText().equals("Ingresa tu nombre de usuario")) {
            // Verifica si el campo de nombre de usuario tiene el texto predeterminado "Ingresa tu nombre de usuario"
            labelUserName.setText(""); // Borra el texto predeterminado para permitir al usuario ingresar su nombre de usuario
            labelUserName.setForeground(Color.black); // Cambia el color del texto del campo de nombre de usuario a negro para indicar que está activo
        }

        if (String.valueOf(labelPasswordUser.getPassword()).isEmpty()) {
            // Verifica si el campo de contraseña está vacío.
            labelPasswordUser.setText("*************"); // Establece el texto predeterminado para ocultar visualmente la contraseña
            labelPasswordUser.setForeground(Color.gray); // Cambia el color del texto del campo de contraseña a gris para indicar que es un texto predeterminado
        }
    }//GEN-LAST:event_labelUserNameMousePressed

    private void labelPasswordUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPasswordUserMousePressed
        if (String.valueOf(labelPasswordUser.getPassword()).equals("*************")) {
            // Verifica si el campo de contraseña tiene el texto predeterminado "*************"
            labelPasswordUser.setText(""); // Borra ese texto para permitir al usuario ingresar su contraseña
            labelPasswordUser.setForeground(Color.black); // Cambia el color del texto del campo de contraseña a negro para indicar que está activo
        }

        if (labelUserName.getText().isEmpty()) {
            // Verifica si el campo de nombre de usuario está vacío
            labelUserName.setText("Ingresa tu nombre de usuario"); // Establece el texto predeterminado
            labelUserName.setForeground(Color.gray); // Cambia el color del texto del campo de nombre de usuario a gris para indicar que es un texto predeterminado
        }
    }//GEN-LAST:event_labelPasswordUserMousePressed

    private void labelPasswordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelPasswordUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelPasswordUserActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (showPassword.isSelected()) {
            labelPasswordUser.setEchoChar((char) 0); // Muestra la contraseña en texto plano
            if (labelPasswordUser.equals("*************")) {
                labelPasswordUser.setText(""); // Limpia el texto predeterminado si está presente
            }
        } else {
            labelPasswordUser.setEchoChar('*'); // Oculta la contraseña con asteriscos
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField labelPasswordUser;
    private javax.swing.JTextField labelUserName;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables
}
